# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_onboard_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard',
            name='computed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
