# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_onboard_computed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='computed',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='debts',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
